# Generated by Django 4.0.6 on 2022-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinomaniaApi', '0002_person_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
